1. Create a NumPy array of integers from 1 to 10.

In [19]:
import numpy as np


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20

In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.


In [ ]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
arr2=np.array([4,5,6])
arr2

array([4, 5, 6])

In [ ]:
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr3=arr1-arr2
arr3

array([-3, -3, -3])

In [ ]:
arr3=arr1*arr2
arr3

array([ 4, 10, 18])

In [ ]:
arr3=arr1/arr2
arr3

array([0.25, 0.4 , 0.5 ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [ ]:
arr4=np.random.rand(100)
arr4

array([0.82736941, 0.49295135, 0.49599104, 0.18932196, 0.46754957,
       0.9033792 , 0.49165579, 0.89171161, 0.13083377, 0.47621792,
       0.54330159, 0.06632493, 0.59548459, 0.65972684, 0.72972858,
       0.85723034, 0.41385146, 0.72452743, 0.48069941, 0.81195318,
       0.6740177 , 0.1766973 , 0.79076111, 0.09836794, 0.49608828,
       0.64084887, 0.39677594, 0.81747067, 0.29551175, 0.60806819,
       0.05113469, 0.34102914, 0.82245707, 0.70702437, 0.01085113,
       0.31067818, 0.71288975, 0.99872431, 0.66016534, 0.34642724,
       0.490243  , 0.89401072, 0.82840344, 0.87525249, 0.51013055,
       0.30391708, 0.45023678, 0.69128129, 0.27788818, 0.50335481,
       0.09044497, 0.25979025, 0.3073229 , 0.04612971, 0.866645  ,
       0.56170696, 0.33606342, 0.06382239, 0.57814043, 0.40673865,
       0.09492817, 0.94655632, 0.83894756, 0.85879581, 0.87384629,
       0.86024943, 0.92743104, 0.3016921 , 0.44759309, 0.37422185,
       0.90920222, 0.18136992, 0.17261581, 0.9729026 , 0.04564

In [ ]:
#mean

In [ ]:
arr5=arr4.mean()
arr5

0.5046210339191336

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr6=np.random.randint(0,20,12)
arr6

array([18, 13, 14,  7,  2,  4, 11,  6,  8,  4, 10, 12])

In [ ]:
arr7=arr6.reshape(3,4)
arr7

array([[18, 13, 14,  7],
       [ 2,  4, 11,  6],
       [ 8,  4, 10, 12]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

8. Create a 5x5 identity matrix using NumPy

In [ ]:
arr=np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b=np.array([4,5,6])
b


array([4, 5, 6])

In [ ]:
a.dot(b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr8=np.random.randint(1,101,10)
arr8

array([ 31,  10, 100,  80,  46,   7,  20,  44,  90,  70])

In [ ]:
arr8.argmax()

2

In [ ]:
arr8.argmin()

5

11.Concatenate two random NumPy arrays horizontally and vertically

In [ ]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('vertical concatenation-\n',c)
print('horizontal concatenation-\n',d)


vertical concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenation-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [ ]:
arr9=np.arange(1,17).reshape(4,4)
print(arr9)
print('sum of each column is',np.sum(arr9,axis=0))
print('sum of each row is',np.sum(arr9,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each row is [28 32 36 40]


13.Find the common elements between two NumPy arrays.

In [ ]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("the common elements between a and b are ",c)

the common elements between a and b are  [5 7 9]


14.Replace all negative values in a NumPy array with zeros

In [ ]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [ ]:
arr10=np.random.randint(1,101,100)
arr10.sort()
arr10

array([ 1,  2,  3,  4,  5,  7,  8,  8,  9,  9, 10, 10, 10, 11, 12, 14, 15,
       15, 15, 16, 17, 18, 18, 19, 19, 20, 21, 22, 23, 24, 27, 27, 27, 28,
       31, 33, 34, 34, 35, 35, 35, 36, 37, 39, 39, 40, 41, 41, 41, 43, 45,
       45, 46, 46, 49, 49, 50, 50, 51, 52, 52, 53, 55, 55, 57, 59, 60, 60,
       61, 63, 63, 64, 65, 65, 65, 69, 69, 70, 71, 71, 72, 73, 73, 73, 78,
       80, 82, 83, 83, 85, 86, 88, 89, 91, 92, 93, 94, 95, 96, 97])

16.Calculate the element-wise absolute difference between two NumPy
arrays

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print("the element-wise absolute differencebetween the two arrays is",c)

the element-wise absolute differencebetween the two arrays is [5 6 7 8 9]


17.Given a 2D NumPy array, extract the first row and the last column

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("First row is\n",firstrow)
print("Last column is\n",lastcol)

First row is
 [1 2 3]
Last column is
 [[3]
 [6]
 [9]]


In [ ]:
18.Slice a 1D NumPy array to get every other element

In [21]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements

In [22]:
arr=np.array([[10,12,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is\n',arr)
print('central 2x2elements include\n',x)

original array is
 [[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2elements include
 [[38 40]
 [50 52]]


20.Reverse a 1D NumPy array using slicing.

In [23]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])